name: 'Create tag in git'
description: 'Creates a tag in git based on the version found in package.json'
inputs:
  github-token:
    description: 'The token to use for interacting with GitHub'
    required: true
  include-build-metadata:
    description: 'Whether to include build metadata in the generated tag (e.g. <build_number>-<short_sha>)'
    required: false
    default: 'false'
outputs:
  tag-name:
    description: 'The name of the tag that was created'
runs:
  using: 'node16'
  main: 'dist/index.js'
