name: Verify PR - Run Unit Tests

on:
  pull_request:
    paths:
      - 'github/actions/get-heroku-application-name/**'

jobs:
  unit-tests:
    name: Unit Tests (Jest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/get-heroku-application-name
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node Modules
        run: yarn

      - name: Run Tests
        run: yarn test:ci

      - name: Post Coverage Results to Pull Request
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
