on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Heroku Application Name
        id: get-heroku-application-name
        uses: invitation-homes/heroku-deployment-workflows/.github/actions/get-heroku-application-name@v1
        with:
          environment: ${{ inputs.environment }}

      - name: Deploy to ${{ inputs.environment }}
        id: deploy-application
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: ${{ steps.get-heroku-application-name.outputs.heroku-application-name }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Create Deployment
        uses: invitation-homes/heroku-deployment-workflows/.github/actions/create-deployment@v1
        with:
          api-token: ${{ secrets.CI_CD_API_TOKEN }}
          environment: ${{ inputs.environment }}
          version: ${{ github.ref_name }}
          is-successful: ${{ steps.deploy-application.outcome == 'success' }}

      - name: Create Production Tag
        uses: invitation-homes/heroku-deployment-workflows/.github/actions/create-commit-tag@v1
        if: ${{ inputs.environment == 'prod' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: false
